[build]
  command = "./netlify-build.sh"
  publish = "dist"
  functions = "netlify/functions-build"

[build.environment]
  NODE_VERSION = "18"
  GROQ_API_KEY = "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"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/placeholder"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 