import { LegalPageShell } from "@/components/LegalPageShell";

export default function AboutUs() {
  return (
    <LegalPageShell pageKey="about">
      <p className="text-base leading-relaxed text-slate-700">
        We provide AI-powered assistants for guidance on wellness topics, lifestyle questions,
        astrology-style entertainment, parenting tips, career ideas, and more. Our service is
        informational and conversational—not a substitute for professional medical, legal, or
        financial advice.
      </p>

      <h2>What we offer</h2>
      <ul>
        <li>Friendly chat experiences tailored to the assistant you choose</li>
        <li>Support for Hindi and English where indicated in the product</li>
        <li>Tools to manage your account and conversation history on your device</li>
      </ul>

      <h2>Important notice</h2>
      <p>
        Outputs are generated by artificial intelligence and may be inaccurate or incomplete.
        Always verify critical information with qualified professionals when it matters to your
        health, safety, or legal obligations.
      </p>

      <p className="text-sm text-slate-500">
        Last updated: May 2026
      </p>
    </LegalPageShell>
  );
}
